### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by nunchuckburns**

### CODE REVIEW

**Comment by benjaminchodroff** [comment]
Sorry, it looks like you forgot to upload to the "mainnet" folder - can you try again?

**Comment by nunchuckburns** [comment]
ok will do

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by benjaminchodroff** [comment]
Great. Can you delete the files that were uploaded into the parent folder? Then, hopefully it should be good to go

**Comment by nunchuckburns** [comment]
I think the deleting is done, hope i am good to go now

**Comment by benjaminchodroff** [comment]
No worries, hope CLWP helps :)

**Pull request merged**
